import { BsGithub, BsLinkedin } from 'react-icons/bs';
import { FaAws, FaSalesforce } from 'react-icons/fa';
import {
  SiAngular,
  SiApollographql,
  SiCircleci,
  SiConfluence,
  SiCss,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGrafana,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJira,
  SiKubernetes,
  SiMariadb,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPrometheus,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiSqlite,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiVim,
  SiWebflow,
  SiWordpress,
  SiZsh,
} from 'react-icons/si';
import { VscVscode } from 'react-icons/vsc';

export const iconMap = {
  Angular: SiAngular,
  'Apollo GraphQL': SiApollographql,
  AWS: FaAws,
  Bash: SiGnubash,
  CircleCI: SiCircleci,
  Confluence: SiConfluence,
  CSS3: SiCss,
  Django: SiDjango,
  Docker: SiDocker,
  Express: SiExpress,
  'Framer Motion': SiFramer,
  Git: SiGit,
  GitHub: BsGithub,
  Github: SiGithub,
  Gitlab: SiGitlab,
  Go: SiGo,
  Grafana: SiGrafana,
  GraphQL: SiGraphql,
  HTML5: SiHtml5,
  JavaScript: SiJavascript,
  Jenkins: SiJenkins,
  Jira: SiJira,
  Kubernetes: SiKubernetes,
  LinkedIn: BsLinkedin,
  MariaDB: SiMariadb,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  'Next.js': SiNextdotjs,
  'Node.js': SiNodedotjs,
  PostgreSQL: SiPostgresql,
  Prisma: SiPrisma,
  Prometheus: SiPrometheus,
  Python: SiPython,
  React: SiReact,
  Redis: SiRedis,
  Redux: SiRedux,
  Salesforce: FaSalesforce,
  SQLite: SiSqlite,
  Tailwind: SiTailwindcss,
  Terraform: SiTerraform,
  TypeScript: SiTypescript,
  Vim: SiVim,
  'Visual Studio Code': VscVscode,
  Webflow: SiWebflow,
  Wordpress: SiWordpress,
  ZSH: SiZsh,
};

export function getIcon(name) {
  return iconMap[name] ?? SiReact;
}
