import { BsGithub, BsLinkedin } from 'react-icons/bs';
import {
  FaAws,
  FaMailBulk,
  FaSalesforce,
  FaShippingFast,
  FaSlack,
} from 'react-icons/fa';
import {
  SiAngular,
  SiApollographql,
  SiBandcamp,
  SiBehance,
  SiBilibili,
  SiBluesky,
  SiBuymeacoffee,
  SiCashapp,
  SiCircleci,
  SiClubhouse,
  SiConfluence,
  SiCss,
  SiDevdotto,
  SiDiaspora,
  SiDirectus,
  SiDiscord,
  SiDjango,
  SiDocker,
  SiDouban,
  SiDribbble,
  SiElement,
  SiExpress,
  SiFacebook,
  SiFacebookgaming,
  SiFacebooklive,
  SiFarcaster,
  SiFlickr,
  SiFoursquare,
  SiFramer,
  SiGit,
  SiGithub,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGoodreads,
  SiGooglecloud,
  SiGooglemessages,
  SiGrafana,
  SiGraphql,
  SiHashnode,
  SiHive,
  SiHtml5,
  SiInstagram,
  SiJavascript,
  SiJenkins,
  SiJira,
  SiKick,
  SiKofi,
  SiKuaishou,
  SiKubernetes,
  SiLemmy,
  SiLetterboxd,
  SiLine,
  SiLinktree,
  SiMariadb,
  SiMastodon,
  SiMatrix,
  SiMedium,
  SiMeetup,
  SiMessenger,
  SiMinds,
  SiMisskey,
  SiMongodb,
  SiMyspace,
  SiMysql,
  SiNextdoor,
  SiNextdotjs,
  SiNodedotjs,
  SiOdnoklassniki,
  SiOnlyfans,
  SiOpencollective,
  SiOpenstreetmap,
  SiPatreon,
  SiPaypal,
  SiPeerlist,
  SiPinterest,
  SiPixelfed,
  SiPlurk,
  SiPolywork,
  SiPostgresql,
  SiPrisma,
  SiProducthunt,
  SiPrometheus,
  SiPython,
  SiQuora,
  SiQzone,
  SiReact,
  SiReddit,
  SiRedis,
  SiRedux,
  SiRevoltdotchat,
  SiRss,
  SiRumble,
  SiSession,
  SiSignal,
  SiSinaweibo,
  SiSnapchat,
  SiSoundcloud,
  SiSpotify,
  SiSqlite,
  SiStackexchange,
  SiStackoverflow,
  SiStrava,
  SiStripe,
  SiSubstack,
  SiTailwindcss,
  SiTelegram,
  SiTerraform,
  SiThreads,
  SiTiktok,
  SiTrello,
  SiTumblr,
  SiTwitch,
  SiTypescript,
  SiUnsplash,
  SiVenmo,
  SiViber,
  SiVim,
  SiVimeo,
  SiVk,
  SiWebflow,
  SiWechat,
  SiWhatsapp,
  SiWoocommerce,
  SiWordpress,
  SiX,
  SiXiaohongshu,
  SiXing,
  SiYcombinator,
  SiYoutube,
  SiZhihu,
  SiZsh,
} from 'react-icons/si';
import { VscVscode } from 'react-icons/vsc';

export const iconMap = {
  // Technologies
  Angular: SiAngular,
  'Apollo GraphQL': SiApollographql,
  AWS: FaAws,

  // Social / community platforms
  Bandcamp: SiBandcamp,
  Bash: SiGnubash,
  Behance: SiBehance,
  Bilibili: SiBilibili,
  Bluesky: SiBluesky,
  'Buy Me a Coffee': SiBuymeacoffee,
  CashApp: SiCashapp,
  CircleCI: SiCircleci,
  Clubhouse: SiClubhouse,
  Confluence: SiConfluence,
  CSS3: SiCss,
  'DEV Community': SiDevdotto,
  Dev: SiDevdotto,
  Diaspora: SiDiaspora,
  'Directus CMS': SiDirectus,
  Discord: SiDiscord,
  Django: SiDjango,
  Docker: SiDocker,
  Douban: SiDouban,
  Dribbble: SiDribbble,
  Element: SiElement,
  Express: SiExpress,
  Facebook: SiFacebook,
  'Facebook Gaming': SiFacebookgaming,
  'Facebook Live': SiFacebooklive,
  Farcaster: SiFarcaster,
  Flickr: SiFlickr,
  Foursquare: SiFoursquare,
  'Framer Motion': SiFramer,
  Git: SiGit,
  GitHub: BsGithub,
  Github: SiGithub,
  Gitlab: SiGitlab,
  Go: SiGo,
  Goodreads: SiGoodreads,
  'Google Cloud Platform': SiGooglecloud,
  'Google Messages': SiGooglemessages,
  Grafana: SiGrafana,
  GraphQL: SiGraphql,
  HackerNews: SiYcombinator,
  Hashnode: SiHashnode,
  Hive: SiHive,
  HTML5: SiHtml5,
  Instagram: SiInstagram,
  JavaScript: SiJavascript,
  Jenkins: SiJenkins,
  Jira: SiJira,
  Kick: SiKick,
  KoFi: SiKofi,
  Kofi: SiKofi,
  Kuaishou: SiKuaishou,
  Kubernetes: SiKubernetes,
  Lemmy: SiLemmy,
  Letterboxd: SiLetterboxd,
  Line: SiLine,
  LinkedIn: BsLinkedin,
  Linktree: SiLinktree,
  MariaDB: SiMariadb,
  Mastodon: SiMastodon,
  Matrix: SiMatrix,
  Medium: SiMedium,
  Meetup: SiMeetup,
  Messenger: SiMessenger,
  Minds: SiMinds,
  Misskey: SiMisskey,
  MongoDB: SiMongodb,
  MySQL: SiMysql,
  Myspace: SiMyspace,
  'Next.js': SiNextdotjs,
  Nextdoor: SiNextdoor,
  'Node.js': SiNodedotjs,
  Odnoklassniki: SiOdnoklassniki,
  OnlyFans: SiOnlyfans,
  'Open Collective': SiOpencollective,
  OpenStreetMap: SiOpenstreetmap,
  Patreon: SiPatreon,
  PayPal: SiPaypal,
  Peerlist: SiPeerlist,
  Pinterest: SiPinterest,
  Pixelfed: SiPixelfed,
  Plurk: SiPlurk,
  Polywork: SiPolywork,
  PostgreSQL: SiPostgresql,
  Prisma: SiPrisma,
  ProductHunt: SiProducthunt,
  Prometheus: SiPrometheus,
  Python: SiPython,
  Quora: SiQuora,
  Qzone: SiQzone,
  React: SiReact,
  Reddit: SiReddit,
  Redis: SiRedis,
  Redux: SiRedux,
  Revolt: SiRevoltdotchat,
  RSS: SiRss,
  Rumble: SiRumble,
  Salesforce: FaSalesforce,
  SendGrid: FaMailBulk,
  Session: SiSession,
  ShipStation: FaShippingFast,
  Signal: SiSignal,
  SinaWeibo: SiSinaweibo,
  Slack: FaSlack,
  Snapchat: SiSnapchat,
  SoundCloud: SiSoundcloud,
  Spotify: SiSpotify,
  SQLite: SiSqlite,
  StackExchange: SiStackexchange,
  StackOverflow: SiStackoverflow,
  Strava: SiStrava,
  Stripe: SiStripe,
  Substack: SiSubstack,
  Tailwind: SiTailwindcss,
  'Tailwind CSS': SiTailwindcss,
  Telegram: SiTelegram,
  Terraform: SiTerraform,
  Threads: SiThreads,
  TikTok: SiTiktok,
  Trello: SiTrello,
  Tumblr: SiTumblr,
  Twitch: SiTwitch,
  TypeScript: SiTypescript,
  Unsplash: SiUnsplash,
  Venmo: SiVenmo,
  Viber: SiViber,
  Vim: SiVim,
  Vimeo: SiVimeo,
  'Visual Studio Code': VscVscode,
  VK: SiVk,
  Webflow: SiWebflow,
  WeChat: SiWechat,
  WhatsApp: SiWhatsapp,
  WooCommerce: SiWoocommerce,
  Wordpress: SiWordpress,
  X: SiX,
  Xiaohongshu: SiXiaohongshu,
  Xing: SiXing,
  YouTube: SiYoutube,
  Zhihu: SiZhihu,
  ZSH: SiZsh,
};

const normalizedIconMap = Object.fromEntries(
  Object.entries(iconMap).map(([name, icon]) => [
    normalizeIconName(name),
    icon,
  ]),
);

const iconAliases = {
  '500px': SiFlickr,
  bsky: SiBluesky,
  buymeacoffee: SiBuymeacoffee,
  devto: SiDevdotto,
  facebookgaming: SiFacebookgaming,
  facebooklive: SiFacebooklive,
  fb: SiFacebook,
  hn: SiYcombinator,
  kofi: SiKofi,
  linkedin: BsLinkedin,
  linktr: SiLinktree,
  producthunt: SiProducthunt,
  revoltchat: SiRevoltdotchat,
  rssfeed: SiRss,
  stackexchange: SiStackexchange,
  stackoverflow: SiStackoverflow,
  twitter: SiX,
  xcom: SiX,
  youtube: SiYoutube,
  yt: SiYoutube,
};

function normalizeIconName(name = '') {
  return String(name)
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '');
}

export function getIcon(name) {
  const normalizedName = normalizeIconName(name);

  return (
    iconMap[name] ??
    normalizedIconMap[normalizedName] ??
    iconAliases[normalizedName] ??
    SiReact
  );
}
