---
version: '3.9'

services:
  tjhorwood:
    container_name: tjhorwood
    image: tjhorwood
    restart: always
    ports:
      - 3031:3031
    build:
      context: /home/thorwood/projects/tjhorwood
      dockerfile: Dockerfile
